version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backendd
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores